### ISSUE TITLE
How to convert Fahrenheit to Celsius with background ?

### ISSUE THREAD

**Issue by msenturk** [blakerutledge/AptHUD#1]

**Comment by blakerutledge** [comment]
Don't bother converting, just look at the JSON coming in and grab the celsius not the farenheight. this will change how the data is visualized in several places.

Also... I forgot this was public and commited my API key. Please change the ajax request urls in the main js file, and get your own key here: https://www.wunderground.com/weather/api I have to make a new one for myself now too and not commit it this time XD

This project was built for a specific use, and i did not write it trying to make reusable. let me know if you get it to work and apologies for hasty code, this is a for-fun project
